name = "decantd"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat_v2"]

main = ".open-next/worker.js"

preview_urls = true

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "decantd-db-dev"
database_id = "b0031528-332f-404f-9f8c-0b3d7de8b37d"

[vars]
NEXT_PUBLIC_ENV = "development"

[env.production]
name = "decantd-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "decantd-db-prod"
database_id = "54b3a0a8-d6df-4ff5-9218-eceeb3568cdf"

[env.production.vars]
NEXT_PUBLIC_ENV = "production"
NODE_ENV = "production"

[env.staging]
name = "decantd-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "decantd-db-staging"
database_id = "a99fee55-5eff-495d-a545-e3f39db1b93f"

[env.staging.vars]
NEXT_PUBLIC_ENV = "staging"
NODE_ENV = "production"

[env.development]
name = "decantd-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "decantd-db-dev"
database_id = "development-placeholder"

[env.development.vars]
NEXT_PUBLIC_ENV = "development"
NODE_ENV = "production"

[env.integration]
name = "decantd-integration"

[[env.integration.d1_databases]]
binding = "DB"
database_name = "decantd-db-dev"
database_id = "b0031528-332f-404f-9f8c-0b3d7de8b37d"

[env.integration.vars]
NEXT_PUBLIC_ENV = "integration"
NODE_ENV = "production"
